//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanningDBEntities : DbContext
    {
        public PlanningDBEntities()
            : base("PlanningDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

        }
    
        public virtual DbSet<Detalle_Tiempo> Detalle_Tiempo { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
        public virtual DbSet<Tarea_Detalle> Tarea_Detalle { get; set; }
        public virtual DbSet<Tipo_Tarea> Tipo_Tarea { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
