//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarea()
        {
            this.Tarea_Detalle = new HashSet<Tarea_Detalle>();
        }
    
        public int ID { get; set; }
        public int TipoID { get; set; }
        public int UsuarioID { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarea_Detalle> Tarea_Detalle { get; set; }
        public virtual Tipo_Tarea Tipo_Tarea { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
