//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea_Detalle
    {
        public int ID { get; set; }
        public int TareaID { get; set; }
        public System.DateTime FechaIni { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
    
        public virtual Detalle_Tiempo Detalle_Tiempo { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
