//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Tiempo
    {
        public int TareaDetalleID { get; set; }
        public System.DateTime FechaLimite { get; set; }
    
        public virtual Tarea_Detalle Tarea_Detalle { get; set; }
    }
}
