//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaAsignadas
    {
        public int DetalleID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Tarea_Detalle Detalle { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
