//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestViewApp.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlanningOtherResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlanningOtherResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestViewApp.Localization.PlanningOtherResources", typeof(PlanningOtherResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion.
        /// </summary>
        public static string Grupo_Descripcion {
            get {
                return ResourceManager.GetString("Grupo_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Creacion.
        /// </summary>
        public static string Grupo_FechaCreacion {
            get {
                return ResourceManager.GetString("Grupo_FechaCreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Grupo_ID {
            get {
                return ResourceManager.GetString("Grupo_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Grupo_Nombre {
            get {
                return ResourceManager.GetString("Grupo_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string GrupoPlural {
            get {
                return ResourceManager.GetString("GrupoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string Rol {
            get {
                return ResourceManager.GetString("Rol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Rol_ID {
            get {
                return ResourceManager.GetString("Rol_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Rol_Nombre {
            get {
                return ResourceManager.GetString("Rol_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        public static string RolPlural {
            get {
                return ResourceManager.GetString("RolPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string Tarea {
            get {
                return ResourceManager.GetString("Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string Tarea_Descripción {
            get {
                return ResourceManager.GetString("Tarea_Descripción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Detalle.
        /// </summary>
        public static string Tarea_Detalle {
            get {
                return ResourceManager.GetString("Tarea_Detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Tarea_Detalle_Estado {
            get {
                return ResourceManager.GetString("Tarea_Detalle_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fin.
        /// </summary>
        public static string Tarea_Detalle_FechaFin {
            get {
                return ResourceManager.GetString("Tarea_Detalle_FechaFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Ini.
        /// </summary>
        public static string Tarea_Detalle_FechaIni {
            get {
                return ResourceManager.GetString("Tarea_Detalle_FechaIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Tarea_Detalle_ID {
            get {
                return ResourceManager.GetString("Tarea_Detalle_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string Tarea_Detalle_Tarea {
            get {
                return ResourceManager.GetString("Tarea_Detalle_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea Detalle.
        /// </summary>
        public static string Tarea_DetallePlural {
            get {
                return ResourceManager.GetString("Tarea_DetallePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Tarea_Estado {
            get {
                return ResourceManager.GetString("Tarea_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Tarea_ID {
            get {
                return ResourceManager.GetString("Tarea_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Tarea_Nombre {
            get {
                return ResourceManager.GetString("Tarea_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string Tarea_Tipo {
            get {
                return ResourceManager.GetString("Tarea_Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarea.
        /// </summary>
        public static string TareaPlural {
            get {
                return ResourceManager.GetString("TareaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Tarea.
        /// </summary>
        public static string Tipo_Tarea {
            get {
                return ResourceManager.GetString("Tipo_Tarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Tipo_Tarea_ID {
            get {
                return ResourceManager.GetString("Tipo_Tarea_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Tipo_Tarea_Nombre {
            get {
                return ResourceManager.GetString("Tipo_Tarea_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Tarea.
        /// </summary>
        public static string Tipo_TareaPlural {
            get {
                return ResourceManager.GetString("Tipo_TareaPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Usuario_Apellido {
            get {
                return ResourceManager.GetString("Usuario_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivo Conf.
        /// </summary>
        public static string Usuario_ArchivoConf {
            get {
                return ResourceManager.GetString("Usuario_ArchivoConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string Usuario_Contraseña {
            get {
                return ResourceManager.GetString("Usuario_Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Usuario_ID {
            get {
                return ResourceManager.GetString("Usuario_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick.
        /// </summary>
        public static string Usuario_Nick {
            get {
                return ResourceManager.GetString("Usuario_Nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Usuario_Nombre {
            get {
                return ResourceManager.GetString("Usuario_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Grupo.
        /// </summary>
        public static string UsuarioGrupo {
            get {
                return ResourceManager.GetString("UsuarioGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        public static string UsuarioGrupo_Grupo {
            get {
                return ResourceManager.GetString("UsuarioGrupo_Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Integrante.
        /// </summary>
        public static string UsuarioGrupo_TipoIntegrante {
            get {
                return ResourceManager.GetString("UsuarioGrupo_TipoIntegrante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UsuarioGrupo_Usuario {
            get {
                return ResourceManager.GetString("UsuarioGrupo_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Grupo.
        /// </summary>
        public static string UsuarioGrupoPlural {
            get {
                return ResourceManager.GetString("UsuarioGrupoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        public static string UsuarioPlural {
            get {
                return ResourceManager.GetString("UsuarioPlural", resourceCulture);
            }
        }
    }
}
